### ISSUE TITLE
Add a setup.py/cfg or update install instructions

### ISSUE THREAD

**Issue by cmungall** [dalito/ucumvert#1]
```
pip install -e .
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /Users/cjm/repos/ucumvert
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```

this did work for me however:

```
hatch run ucumvert
Enter UCUM unit code to parse, or 'q' to quit.
```

but I also needed to add pydot to the dependencies to avoid runtime error

**Comment by dalito** [comment]
Hi Chris, thanks for testing. The install error may be due to a too old version of pip. Was you pip newer than 21.2?

I added a try..except on the use of pydot so that it is optional. It was convenient during grammar development but it is of no further use.

I added some more UCUM aliases and units and fixed an edge case with annotations.
